version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: florian-garage_ui_1
      APP_PORT: 8080

  garage:
    image: dxflrs/garage:v2.4.1@sha256:9c96caa2612d3411acc5b0e6701fb238dbfba33e533a6d7d3d811a4b12d0d020
    user: "1000:1000"
    restart: on-failure
    command: ["/garage", "server"]
    environment:
      GARAGE_RPC_SECRET: ${APP_SEED}
      GARAGE_ADMIN_TOKEN: ${APP_SEED}
    ports:
      - "3900:3900" # S3 API
    volumes:
      - ${APP_DATA_DIR}/garage.toml:/etc/garage.toml:ro
      - ${APP_DATA_DIR}/data/meta:/var/lib/garage/meta
      - ${APP_DATA_DIR}/data/data:/var/lib/garage/data

  ui:
    image: noooste/garage-ui:v0.13.0@sha256:a1444fa10585a0efc8ce3c33ebda873e5714d51dbc8f7f49d00143ff3b72fcc2
    restart: on-failure
    environment:
      GARAGE_UI_SERVER_HOST: "0.0.0.0"
      GARAGE_UI_SERVER_PORT: "8080"
      GARAGE_UI_GARAGE_ENDPOINT: http://florian-garage_garage_1:3900
      GARAGE_UI_GARAGE_ADMIN_ENDPOINT: http://florian-garage_garage_1:3903
      GARAGE_UI_GARAGE_ADMIN_TOKEN: ${APP_SEED}
      GARAGE_UI_GARAGE_REGION: garage
    depends_on:
      - garage
